export const lorem = `Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Integer lacinia. Nullam dapibus fermentum ipsum. Integer vulputate sem a nibh rutrum consequat. Maecenas aliquet accumsan leo. Nullam eget nisl. Praesent dapibus. Aliquam erat volutpat. Integer imperdiet lectus quis justo. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Fusce suscipit libero eget elit. Curabitur vitae diam non enim vestibulum interdum. Etiam egestas wisi a erat. Suspendisse nisl. Suspendisse sagittis ultrices augue. Fusce suscipit libero eget elit. In sem justo, commodo ut, suscipit at, pharetra vitae, orci. Nullam dapibus fermentum ipsum. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat.

Praesent dapibus. Nulla non lectus sed nisl molestie malesuada. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor. Fusce aliquam vestibulum ipsum. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. In convallis. Duis risus. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Maecenas aliquet accumsan leo. Fusce consectetuer risus a nunc. Etiam commodo dui eget wisi. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Integer malesuada. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Curabitur sagittis hendrerit ante. Fusce dui leo, imperdiet in, aliquam sit amet, feugiat eu, orci. Integer lacinia. Nam quis nulla. Etiam quis quam. Etiam posuere lacus quis dolor.

Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Maecenas libero. Sed elit dui, pellentesque a, faucibus vel, interdum nec, diam. Fusce nibh. Mauris elementum mauris vitae tortor. Aenean id metus id velit ullamcorper pulvinar. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. In convallis. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Nulla non arcu lacinia neque faucibus fringilla. Aenean vel massa quis mauris vehicula lacinia. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Praesent dapibus. Aliquam id dolor.

Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Aenean placerat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Et harum quidem rerum facilis est et expedita distinctio. Morbi scelerisque luctus velit. In enim a arcu imperdiet malesuada. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Pellentesque ipsum. Etiam commodo dui eget wisi. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Mauris tincidunt sem sed arcu. Suspendisse sagittis ultrices augue.

Integer in sapien. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Integer in sapien. Maecenas libero. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede. Phasellus rhoncus. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Pellentesque sapien. Nullam eget nisl. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Fusce aliquam vestibulum ipsum. Aliquam ante. Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante. Nullam eget nisl. Aenean vel massa quis mauris vehicula lacinia. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero.`;
