export const subjectMockup = [
  {
    id: "626fd9f86196cc28d7e46d9f",
    name: "Bolton",
    goal: "Proident ipsum adipisicing aliqua culpa nisi officia voluptate mollit reprehenderit officia tempor non. Quis cillum proident ut duis labore pariatur enim veniam aliqua in occaecat. Deserunt mollit deserunt dolore nisi anim id do enim eiusmod commodo nisi dolore nostrud.\r\n",
    supervisor: "626fd9f8d9032c6e6a9df71b",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f867643c21ac62019e",
    name: "Duncan",
    goal: "Est amet quis consectetur dolore exercitation amet. Occaecat eu ea officia in pariatur tempor exercitation. Ea ea culpa ea sint elit est aliquip cillum nulla laborum. Laboris adipisicing enim occaecat sunt est. Qui cillum consequat tempor dolore pariatur sit sit proident commodo dolore.\r\n",
    supervisor: "626fd9f89f48771b8ab18751",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f809b1dba48a3c84dc",
    name: "Shelia",
    goal: "Excepteur do enim consequat pariatur commodo laborum. Mollit commodo consectetur elit minim id adipisicing laboris ut tempor et ipsum dolor duis. Ex ea aliquip elit do reprehenderit nostrud enim irure reprehenderit qui et. Laborum enim nostrud aliqua irure eiusmod duis. Deserunt dolore elit non anim. Reprehenderit culpa incididunt exercitation anim eiusmod est qui eu in qui ipsum excepteur ad.\r\n",
    supervisor: "626fd9f8ebaa3246c829a083",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f83ae98774d12c2b5c",
    name: "Jackie",
    goal: "Pariatur proident aute magna mollit dolor esse sunt reprehenderit excepteur nulla. Eiusmod quis aliqua enim in. Fugiat ut cupidatat incididunt ut aliqua ullamco aliquip. Officia sunt enim nisi adipisicing ad voluptate eiusmod excepteur.\r\n",
    supervisor: "626fd9f8a459619a261024e5",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f818d747862fa2974f",
    name: "Bray",
    goal: "Nisi irure mollit exercitation exercitation velit nostrud nisi. In sit qui aliqua magna duis ut occaecat qui id aliqua. Voluptate qui id non commodo nostrud nulla exercitation nulla quis est quis. Nulla Lorem enim culpa irure fugiat sint Lorem elit ea consectetur commodo veniam non. Ex culpa aute aute tempor mollit in consectetur sit ut eiusmod deserunt qui. Non ea eiusmod cupidatat deserunt Lorem duis occaecat proident laboris dolor ipsum. Nostrud culpa ut ad et.\r\n",
    supervisor: "626fd9f845921433e4589080",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f85249efd3ad9f419e",
    name: "Kristen",
    goal: "Anim do do officia in enim amet irure officia pariatur nostrud. Cupidatat est culpa aliquip exercitation nisi exercitation nisi. Velit veniam pariatur veniam pariatur occaecat dolor cillum labore. Consequat magna et incididunt nostrud sunt amet in sint deserunt mollit laboris veniam enim. Lorem veniam adipisicing adipisicing qui aliqua Lorem eiusmod. Ullamco elit do ullamco non.\r\n",
    supervisor: "626fd9f87a80a324ab577b16",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8253f1672491be227",
    name: "Nona",
    goal: "Enim consectetur anim laboris sit ut. Ea ad pariatur enim sint. Id labore eu nostrud aute nisi sint do excepteur eu eu pariatur anim. Ad esse proident incididunt consectetur. Dolor sit duis esse fugiat voluptate proident consectetur ipsum id reprehenderit aute velit consequat.\r\n",
    supervisor: "626fd9f852581208ab4371e6",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8f4acd492712e65bb",
    name: "Oconnor",
    goal: "Officia commodo laboris reprehenderit laboris enim incididunt et laboris cillum eu consectetur esse. Ex enim eu irure voluptate exercitation nostrud occaecat. Excepteur et eu irure consectetur culpa dolor aute esse aliquip tempor minim tempor. Irure aliqua do cupidatat commodo minim.\r\n",
    supervisor: "626fd9f8318fca5953030dba",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8773618a0d2b3cae2",
    name: "Wilkinson",
    goal: "Eiusmod sunt laboris irure labore commodo duis voluptate non magna ipsum ut exercitation. Reprehenderit elit in culpa ipsum tempor enim minim ullamco. Ad dolore magna eiusmod non adipisicing velit anim ex mollit commodo sint. Aliquip veniam aliqua velit labore officia sunt.\r\n",
    supervisor: "626fd9f88bc3557544dad45c",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f86f9a221eb185b213",
    name: "Boyd",
    goal: "Tempor elit veniam incididunt voluptate cillum reprehenderit cillum eiusmod fugiat officia et. Cupidatat nisi id sunt exercitation incididunt proident nulla eu sint reprehenderit est eiusmod. Lorem quis nostrud occaecat ea.\r\n",
    supervisor: "626fd9f889dbca6ec0ef7eea",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f83f23bb2ca4fefe7a",
    name: "Ora",
    goal: "Nisi in nisi aliquip et pariatur pariatur est. Proident nisi id eiusmod laborum minim ullamco ipsum non id ea aliquip ullamco. In commodo anim non cillum sint incididunt sunt ad labore nisi dolore velit duis proident. Nisi magna ullamco do aliqua amet amet. Ex velit anim nostrud velit.\r\n",
    supervisor: "626fd9f8e5026c89e4277f6c",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f818558b5e5ecf7623",
    name: "Della",
    goal: "Ex ea eiusmod labore est dolor aute eu. Consectetur ullamco voluptate reprehenderit adipisicing esse eiusmod ipsum voluptate velit. Esse anim eiusmod velit non aliquip laboris excepteur voluptate. Anim eu reprehenderit nostrud reprehenderit nostrud commodo deserunt aliqua adipisicing labore aliqua est.\r\n",
    supervisor: "626fd9f8670c39228dd770bc",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8d10f688e24d25625",
    name: "Esther",
    goal: "Tempor est duis enim qui enim esse non dolor Lorem est officia laboris nulla ullamco. Laboris in consequat aliqua laborum dolor in ullamco. Id incididunt aliquip est ex proident ad ad ad pariatur Lorem ea dolor cillum. Cillum eiusmod eiusmod incididunt officia anim velit occaecat. Esse duis ea consequat duis quis excepteur in adipisicing sit voluptate eiusmod nulla duis culpa.\r\n",
    supervisor: "626fd9f84538ff0f8ccd9a29",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8207bf7aaa5232313",
    name: "Hollie",
    goal: "Anim ipsum do ipsum cupidatat cupidatat ea velit sit consectetur sit. Est esse cupidatat exercitation laboris. In in cupidatat cupidatat id Lorem Lorem consectetur laboris. Nulla qui irure ipsum nulla officia fugiat sit minim in ut.\r\n",
    supervisor: "626fd9f81eba53abde6d8d13",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f873dbb44109c0fcb7",
    name: "Savannah",
    goal: "Id sunt incididunt exercitation dolore. Fugiat officia sit qui tempor anim laboris ullamco quis excepteur irure voluptate est voluptate adipisicing. Non cillum irure id incididunt in laboris consequat et labore.\r\n",
    supervisor: "626fd9f8b65656e0d4f976d8",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8f5d0599d83e475ce",
    name: "Adeline",
    goal: "Deserunt non voluptate deserunt pariatur cillum sint. Cupidatat eu consectetur consequat reprehenderit officia ipsum deserunt in sunt id et Lorem consectetur cupidatat. Qui et dolor nisi ea aute veniam incididunt aute nulla magna cillum magna et. Labore irure magna officia elit mollit reprehenderit ad id amet. Exercitation enim voluptate quis sint do reprehenderit veniam qui. Aliqua ullamco irure in non excepteur enim. In tempor Lorem et eu sint ullamco elit quis in.\r\n",
    supervisor: "626fd9f877b6a63b7840603b",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f871e1eee353c0942d",
    name: "Gina",
    goal: "Aute cillum nisi in officia elit anim fugiat culpa magna. Minim consequat proident nulla cillum qui veniam Lorem nisi est do Lorem eiusmod ipsum ut. Ex amet anim anim dolore laborum consequat est aliquip veniam. Laboris Lorem amet duis voluptate consequat labore magna elit reprehenderit adipisicing. Commodo Lorem ex esse quis eu proident amet ut nisi id anim ullamco excepteur eiusmod. Dolore ex excepteur pariatur mollit et et cupidatat enim ut est consequat consectetur non. Et deserunt consectetur ut officia duis occaecat eu laboris ut aliqua ut sit voluptate ad.\r\n",
    supervisor: "626fd9f800dfcf14b8c0a86c",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8dc9b36f049b65f2a",
    name: "Sykes",
    goal: "Elit elit proident adipisicing veniam in magna velit irure nostrud consectetur non. Mollit ad magna sit sint esse. Laboris sunt incididunt eu veniam sunt voluptate aliquip. Ullamco do Lorem nostrud deserunt quis ex et duis est.\r\n",
    supervisor: "626fd9f8b7016da1ac9ea0dd",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8114ac4549ca4bd09",
    name: "Copeland",
    goal: "Excepteur nisi ut ad nulla voluptate qui amet veniam velit. Nulla irure aliquip veniam dolore eu aliqua incididunt. Ullamco cillum dolore ad ad exercitation cupidatat laborum aliquip quis sunt duis cupidatat elit. Elit officia sint labore ipsum excepteur minim ipsum occaecat laboris cupidatat ad. Nisi consequat amet cillum ex non deserunt tempor ut nisi magna id nostrud incididunt veniam. Sit aliquip ipsum Lorem irure et dolor aliquip reprehenderit in nulla commodo cillum amet. Amet nostrud eiusmod ullamco sit nulla sunt irure dolore quis est ex excepteur.\r\n",
    supervisor: "626fd9f8667d093f121cd8a3",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8443c3d87093327e5",
    name: "Candace",
    goal: "Ea sit laborum est tempor ex minim anim proident sit. Ea in duis enim nostrud nisi voluptate. Adipisicing aliqua dolore qui nisi dolore labore esse laboris fugiat ullamco dolor enim excepteur.\r\n",
    supervisor: "626fd9f8a39537cdd4f5630e",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8a01c6030ddbe09bc",
    name: "Lori",
    goal: "Voluptate mollit est proident mollit dolor ea eiusmod tempor cillum qui sint. Eiusmod duis velit eu est enim ullamco dolor qui est sunt fugiat. Ad id aute ex ipsum mollit proident sunt velit adipisicing. Cupidatat in aute eiusmod minim magna nulla. Labore laboris culpa sunt est tempor ullamco consectetur sint non cillum duis voluptate sit cillum. Incididunt dolor occaecat cupidatat aliqua irure dolore laboris velit nostrud voluptate labore excepteur qui. Cillum occaecat cupidatat aliqua qui quis ea cillum consequat occaecat ea sint.\r\n",
    supervisor: "626fd9f8c16a48307134641c",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f850d9ec0400faf7a7",
    name: "Ayala",
    goal: "Dolor excepteur adipisicing id nisi amet do reprehenderit tempor velit magna. Ut id magna do duis in deserunt. Eiusmod tempor laborum elit velit voluptate. Fugiat laborum quis consequat pariatur duis labore ex in. Nisi aliquip consectetur consectetur aute nulla ut in pariatur ullamco incididunt sint aute proident do. Sit dolor commodo aute cupidatat sunt nostrud nulla quis ut. Adipisicing ipsum sint consectetur sunt elit ea.\r\n",
    supervisor: "626fd9f8f35d9567ef4e9db0",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8699a0f061172c817",
    name: "Page",
    goal: "Aliquip anim reprehenderit reprehenderit deserunt nulla deserunt Lorem laborum labore pariatur mollit ut aute elit. Do aliquip consectetur dolore tempor. Lorem pariatur quis do aute deserunt laboris ut commodo ut culpa veniam voluptate culpa cillum. Eiusmod in ullamco est et sunt. Tempor dolore labore enim commodo velit non reprehenderit ut magna aute quis id irure do.\r\n",
    supervisor: "626fd9f833b9b66e47b4561d",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8a366518f9b75c50b",
    name: "Woodard",
    goal: "Commodo nisi ullamco non ad voluptate pariatur velit occaecat minim ut proident eu. Nisi tempor qui ut culpa nostrud. Elit consectetur nostrud laborum proident veniam laboris minim aliquip est aute elit id. Quis ut duis incididunt ipsum pariatur nulla veniam amet proident. Pariatur laboris sunt cupidatat occaecat magna non quis deserunt officia quis proident elit irure nostrud.\r\n",
    supervisor: "626fd9f8e93a8291071e0576",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8cef4fb0b409d0717",
    name: "Green",
    goal: "Ipsum velit ea incididunt et. Irure aliquip incididunt magna culpa anim commodo tempor nostrud labore ut velit nulla consequat. Anim deserunt dolore enim dolor aute incididunt excepteur elit incididunt fugiat qui deserunt quis officia.\r\n",
    supervisor: "626fd9f8965cafb3d3f2ec3a",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f800c79167c6d70999",
    name: "Clarke",
    goal: "Laboris non exercitation aute amet. Ipsum do laboris ut amet occaecat eiusmod elit in id ipsum elit in ad laboris. In adipisicing eu amet aliqua cillum.\r\n",
    supervisor: "626fd9f841a23eef7b5afa4b",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8fb8a223acab75d44",
    name: "Kaufman",
    goal: "Esse qui ex mollit nisi. In commodo pariatur pariatur excepteur reprehenderit officia pariatur eiusmod sint. Velit officia enim consectetur exercitation ipsum dolore quis pariatur aliqua et minim.\r\n",
    supervisor: "626fd9f85b6add3c7acdfb4c",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8a6b31d3a2d3b4121",
    name: "Chapman",
    goal: "Qui ad commodo exercitation sit elit veniam excepteur fugiat fugiat incididunt fugiat. Cupidatat proident est commodo tempor elit nostrud esse labore voluptate mollit irure et deserunt. Elit anim deserunt exercitation ut nostrud officia veniam eiusmod laborum eiusmod deserunt reprehenderit id adipisicing. Qui aute reprehenderit in quis quis non quis nostrud sint ad proident ex. Proident ea fugiat ea adipisicing nulla. Do exercitation elit aliqua do. Laborum pariatur laboris occaecat mollit pariatur ex amet mollit deserunt sunt.\r\n",
    supervisor: "626fd9f806cf069779d48f5d",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f87a2dc49af1579a9c",
    name: "Riddle",
    goal: "Adipisicing laborum nisi ut aliquip incididunt dolore nulla ut pariatur. Aliqua mollit irure sit qui ut. Sit velit ullamco duis ad sunt elit esse laborum nisi. Magna quis cillum elit cupidatat qui velit amet consectetur mollit magna irure eiusmod. Duis occaecat enim aute nostrud elit non do in quis qui qui exercitation consequat et. Aliqua exercitation qui nostrud occaecat magna mollit elit aliquip ut ullamco incididunt mollit occaecat. In est aliqua nulla consequat sunt deserunt.\r\n",
    supervisor: "626fd9f88279c357591b949b",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f819799a5dee61951f",
    name: "Webb",
    goal: "Occaecat id officia cupidatat commodo aute exercitation mollit esse mollit amet proident velit eiusmod. Fugiat commodo ea exercitation commodo est esse duis magna adipisicing laborum esse irure. Do labore ullamco minim voluptate culpa Lorem proident fugiat.\r\n",
    supervisor: "626fd9f8f1751b741f1ca770",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f86ceba2e0e308005c",
    name: "Georgette",
    goal: "Deserunt cupidatat eu dolor culpa. Ullamco cupidatat sunt nulla consectetur mollit officia commodo eiusmod tempor excepteur nisi. Voluptate consequat incididunt tempor nulla elit aliquip veniam et aute. Occaecat minim enim in nulla non ea fugiat minim minim. Adipisicing consectetur duis aliqua tempor officia elit consequat occaecat ex ex veniam magna voluptate ex. Mollit quis Lorem ex cupidatat deserunt adipisicing. Id non et ex anim.\r\n",
    supervisor: "626fd9f8c71d87b49cccdf36",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f86196cc28d7e46d9f",
    name: "Bolton",
    goal: "Proident ipsum adipisicing aliqua culpa nisi officia voluptate mollit reprehenderit officia tempor non. Quis cillum proident ut duis labore pariatur enim veniam aliqua in occaecat. Deserunt mollit deserunt dolore nisi anim id do enim eiusmod commodo nisi dolore nostrud.\r\n",
    supervisor: "626fd9f8d9032c6e6a9df71b",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f867643c21ac62019e",
    name: "Duncan",
    goal: "Est amet quis consectetur dolore exercitation amet. Occaecat eu ea officia in pariatur tempor exercitation. Ea ea culpa ea sint elit est aliquip cillum nulla laborum. Laboris adipisicing enim occaecat sunt est. Qui cillum consequat tempor dolore pariatur sit sit proident commodo dolore.\r\n",
    supervisor: "626fd9f89f48771b8ab18751",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f809b1dba48a3c84dc",
    name: "Shelia",
    goal: "Excepteur do enim consequat pariatur commodo laborum. Mollit commodo consectetur elit minim id adipisicing laboris ut tempor et ipsum dolor duis. Ex ea aliquip elit do reprehenderit nostrud enim irure reprehenderit qui et. Laborum enim nostrud aliqua irure eiusmod duis. Deserunt dolore elit non anim. Reprehenderit culpa incididunt exercitation anim eiusmod est qui eu in qui ipsum excepteur ad.\r\n",
    supervisor: "626fd9f8ebaa3246c829a083",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f83ae98774d12c2b5c",
    name: "Jackie",
    goal: "Pariatur proident aute magna mollit dolor esse sunt reprehenderit excepteur nulla. Eiusmod quis aliqua enim in. Fugiat ut cupidatat incididunt ut aliqua ullamco aliquip. Officia sunt enim nisi adipisicing ad voluptate eiusmod excepteur.\r\n",
    supervisor: "626fd9f8a459619a261024e5",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f818d747862fa2974f",
    name: "Bray",
    goal: "Nisi irure mollit exercitation exercitation velit nostrud nisi. In sit qui aliqua magna duis ut occaecat qui id aliqua. Voluptate qui id non commodo nostrud nulla exercitation nulla quis est quis. Nulla Lorem enim culpa irure fugiat sint Lorem elit ea consectetur commodo veniam non. Ex culpa aute aute tempor mollit in consectetur sit ut eiusmod deserunt qui. Non ea eiusmod cupidatat deserunt Lorem duis occaecat proident laboris dolor ipsum. Nostrud culpa ut ad et.\r\n",
    supervisor: "626fd9f845921433e4589080",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f85249efd3ad9f419e",
    name: "Kristen",
    goal: "Anim do do officia in enim amet irure officia pariatur nostrud. Cupidatat est culpa aliquip exercitation nisi exercitation nisi. Velit veniam pariatur veniam pariatur occaecat dolor cillum labore. Consequat magna et incididunt nostrud sunt amet in sint deserunt mollit laboris veniam enim. Lorem veniam adipisicing adipisicing qui aliqua Lorem eiusmod. Ullamco elit do ullamco non.\r\n",
    supervisor: "626fd9f87a80a324ab577b16",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8253f1672491be227",
    name: "Nona",
    goal: "Enim consectetur anim laboris sit ut. Ea ad pariatur enim sint. Id labore eu nostrud aute nisi sint do excepteur eu eu pariatur anim. Ad esse proident incididunt consectetur. Dolor sit duis esse fugiat voluptate proident consectetur ipsum id reprehenderit aute velit consequat.\r\n",
    supervisor: "626fd9f852581208ab4371e6",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8f4acd492712e65bb",
    name: "Oconnor",
    goal: "Officia commodo laboris reprehenderit laboris enim incididunt et laboris cillum eu consectetur esse. Ex enim eu irure voluptate exercitation nostrud occaecat. Excepteur et eu irure consectetur culpa dolor aute esse aliquip tempor minim tempor. Irure aliqua do cupidatat commodo minim.\r\n",
    supervisor: "626fd9f8318fca5953030dba",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8773618a0d2b3cae2",
    name: "Wilkinson",
    goal: "Eiusmod sunt laboris irure labore commodo duis voluptate non magna ipsum ut exercitation. Reprehenderit elit in culpa ipsum tempor enim minim ullamco. Ad dolore magna eiusmod non adipisicing velit anim ex mollit commodo sint. Aliquip veniam aliqua velit labore officia sunt.\r\n",
    supervisor: "626fd9f88bc3557544dad45c",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f86f9a221eb185b213",
    name: "Boyd",
    goal: "Tempor elit veniam incididunt voluptate cillum reprehenderit cillum eiusmod fugiat officia et. Cupidatat nisi id sunt exercitation incididunt proident nulla eu sint reprehenderit est eiusmod. Lorem quis nostrud occaecat ea.\r\n",
    supervisor: "626fd9f889dbca6ec0ef7eea",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f83f23bb2ca4fefe7a",
    name: "Ora",
    goal: "Nisi in nisi aliquip et pariatur pariatur est. Proident nisi id eiusmod laborum minim ullamco ipsum non id ea aliquip ullamco. In commodo anim non cillum sint incididunt sunt ad labore nisi dolore velit duis proident. Nisi magna ullamco do aliqua amet amet. Ex velit anim nostrud velit.\r\n",
    supervisor: "626fd9f8e5026c89e4277f6c",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f818558b5e5ecf7623",
    name: "Della",
    goal: "Ex ea eiusmod labore est dolor aute eu. Consectetur ullamco voluptate reprehenderit adipisicing esse eiusmod ipsum voluptate velit. Esse anim eiusmod velit non aliquip laboris excepteur voluptate. Anim eu reprehenderit nostrud reprehenderit nostrud commodo deserunt aliqua adipisicing labore aliqua est.\r\n",
    supervisor: "626fd9f8670c39228dd770bc",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8d10f688e24d25625",
    name: "Esther",
    goal: "Tempor est duis enim qui enim esse non dolor Lorem est officia laboris nulla ullamco. Laboris in consequat aliqua laborum dolor in ullamco. Id incididunt aliquip est ex proident ad ad ad pariatur Lorem ea dolor cillum. Cillum eiusmod eiusmod incididunt officia anim velit occaecat. Esse duis ea consequat duis quis excepteur in adipisicing sit voluptate eiusmod nulla duis culpa.\r\n",
    supervisor: "626fd9f84538ff0f8ccd9a29",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8207bf7aaa5232313",
    name: "Hollie",
    goal: "Anim ipsum do ipsum cupidatat cupidatat ea velit sit consectetur sit. Est esse cupidatat exercitation laboris. In in cupidatat cupidatat id Lorem Lorem consectetur laboris. Nulla qui irure ipsum nulla officia fugiat sit minim in ut.\r\n",
    supervisor: "626fd9f81eba53abde6d8d13",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f873dbb44109c0fcb7",
    name: "Savannah",
    goal: "Id sunt incididunt exercitation dolore. Fugiat officia sit qui tempor anim laboris ullamco quis excepteur irure voluptate est voluptate adipisicing. Non cillum irure id incididunt in laboris consequat et labore.\r\n",
    supervisor: "626fd9f8b65656e0d4f976d8",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8f5d0599d83e475ce",
    name: "Adeline",
    goal: "Deserunt non voluptate deserunt pariatur cillum sint. Cupidatat eu consectetur consequat reprehenderit officia ipsum deserunt in sunt id et Lorem consectetur cupidatat. Qui et dolor nisi ea aute veniam incididunt aute nulla magna cillum magna et. Labore irure magna officia elit mollit reprehenderit ad id amet. Exercitation enim voluptate quis sint do reprehenderit veniam qui. Aliqua ullamco irure in non excepteur enim. In tempor Lorem et eu sint ullamco elit quis in.\r\n",
    supervisor: "626fd9f877b6a63b7840603b",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f871e1eee353c0942d",
    name: "Gina",
    goal: "Aute cillum nisi in officia elit anim fugiat culpa magna. Minim consequat proident nulla cillum qui veniam Lorem nisi est do Lorem eiusmod ipsum ut. Ex amet anim anim dolore laborum consequat est aliquip veniam. Laboris Lorem amet duis voluptate consequat labore magna elit reprehenderit adipisicing. Commodo Lorem ex esse quis eu proident amet ut nisi id anim ullamco excepteur eiusmod. Dolore ex excepteur pariatur mollit et et cupidatat enim ut est consequat consectetur non. Et deserunt consectetur ut officia duis occaecat eu laboris ut aliqua ut sit voluptate ad.\r\n",
    supervisor: "626fd9f800dfcf14b8c0a86c",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8dc9b36f049b65f2a",
    name: "Sykes",
    goal: "Elit elit proident adipisicing veniam in magna velit irure nostrud consectetur non. Mollit ad magna sit sint esse. Laboris sunt incididunt eu veniam sunt voluptate aliquip. Ullamco do Lorem nostrud deserunt quis ex et duis est.\r\n",
    supervisor: "626fd9f8b7016da1ac9ea0dd",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8114ac4549ca4bd09",
    name: "Copeland",
    goal: "Excepteur nisi ut ad nulla voluptate qui amet veniam velit. Nulla irure aliquip veniam dolore eu aliqua incididunt. Ullamco cillum dolore ad ad exercitation cupidatat laborum aliquip quis sunt duis cupidatat elit. Elit officia sint labore ipsum excepteur minim ipsum occaecat laboris cupidatat ad. Nisi consequat amet cillum ex non deserunt tempor ut nisi magna id nostrud incididunt veniam. Sit aliquip ipsum Lorem irure et dolor aliquip reprehenderit in nulla commodo cillum amet. Amet nostrud eiusmod ullamco sit nulla sunt irure dolore quis est ex excepteur.\r\n",
    supervisor: "626fd9f8667d093f121cd8a3",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8443c3d87093327e5",
    name: "Candace",
    goal: "Ea sit laborum est tempor ex minim anim proident sit. Ea in duis enim nostrud nisi voluptate. Adipisicing aliqua dolore qui nisi dolore labore esse laboris fugiat ullamco dolor enim excepteur.\r\n",
    supervisor: "626fd9f8a39537cdd4f5630e",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8a01c6030ddbe09bc",
    name: "Lori",
    goal: "Voluptate mollit est proident mollit dolor ea eiusmod tempor cillum qui sint. Eiusmod duis velit eu est enim ullamco dolor qui est sunt fugiat. Ad id aute ex ipsum mollit proident sunt velit adipisicing. Cupidatat in aute eiusmod minim magna nulla. Labore laboris culpa sunt est tempor ullamco consectetur sint non cillum duis voluptate sit cillum. Incididunt dolor occaecat cupidatat aliqua irure dolore laboris velit nostrud voluptate labore excepteur qui. Cillum occaecat cupidatat aliqua qui quis ea cillum consequat occaecat ea sint.\r\n",
    supervisor: "626fd9f8c16a48307134641c",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f850d9ec0400faf7a7",
    name: "Ayala",
    goal: "Dolor excepteur adipisicing id nisi amet do reprehenderit tempor velit magna. Ut id magna do duis in deserunt. Eiusmod tempor laborum elit velit voluptate. Fugiat laborum quis consequat pariatur duis labore ex in. Nisi aliquip consectetur consectetur aute nulla ut in pariatur ullamco incididunt sint aute proident do. Sit dolor commodo aute cupidatat sunt nostrud nulla quis ut. Adipisicing ipsum sint consectetur sunt elit ea.\r\n",
    supervisor: "626fd9f8f35d9567ef4e9db0",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8699a0f061172c817",
    name: "Page",
    goal: "Aliquip anim reprehenderit reprehenderit deserunt nulla deserunt Lorem laborum labore pariatur mollit ut aute elit. Do aliquip consectetur dolore tempor. Lorem pariatur quis do aute deserunt laboris ut commodo ut culpa veniam voluptate culpa cillum. Eiusmod in ullamco est et sunt. Tempor dolore labore enim commodo velit non reprehenderit ut magna aute quis id irure do.\r\n",
    supervisor: "626fd9f833b9b66e47b4561d",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8a366518f9b75c50b",
    name: "Woodard",
    goal: "Commodo nisi ullamco non ad voluptate pariatur velit occaecat minim ut proident eu. Nisi tempor qui ut culpa nostrud. Elit consectetur nostrud laborum proident veniam laboris minim aliquip est aute elit id. Quis ut duis incididunt ipsum pariatur nulla veniam amet proident. Pariatur laboris sunt cupidatat occaecat magna non quis deserunt officia quis proident elit irure nostrud.\r\n",
    supervisor: "626fd9f8e93a8291071e0576",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8cef4fb0b409d0717",
    name: "Green",
    goal: "Ipsum velit ea incididunt et. Irure aliquip incididunt magna culpa anim commodo tempor nostrud labore ut velit nulla consequat. Anim deserunt dolore enim dolor aute incididunt excepteur elit incididunt fugiat qui deserunt quis officia.\r\n",
    supervisor: "626fd9f8965cafb3d3f2ec3a",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f800c79167c6d70999",
    name: "Clarke",
    goal: "Laboris non exercitation aute amet. Ipsum do laboris ut amet occaecat eiusmod elit in id ipsum elit in ad laboris. In adipisicing eu amet aliqua cillum.\r\n",
    supervisor: "626fd9f841a23eef7b5afa4b",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8fb8a223acab75d44",
    name: "Kaufman",
    goal: "Esse qui ex mollit nisi. In commodo pariatur pariatur excepteur reprehenderit officia pariatur eiusmod sint. Velit officia enim consectetur exercitation ipsum dolore quis pariatur aliqua et minim.\r\n",
    supervisor: "626fd9f85b6add3c7acdfb4c",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8a6b31d3a2d3b4121",
    name: "Chapman",
    goal: "Qui ad commodo exercitation sit elit veniam excepteur fugiat fugiat incididunt fugiat. Cupidatat proident est commodo tempor elit nostrud esse labore voluptate mollit irure et deserunt. Elit anim deserunt exercitation ut nostrud officia veniam eiusmod laborum eiusmod deserunt reprehenderit id adipisicing. Qui aute reprehenderit in quis quis non quis nostrud sint ad proident ex. Proident ea fugiat ea adipisicing nulla. Do exercitation elit aliqua do. Laborum pariatur laboris occaecat mollit pariatur ex amet mollit deserunt sunt.\r\n",
    supervisor: "626fd9f806cf069779d48f5d",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f87a2dc49af1579a9c",
    name: "Riddle",
    goal: "Adipisicing laborum nisi ut aliquip incididunt dolore nulla ut pariatur. Aliqua mollit irure sit qui ut. Sit velit ullamco duis ad sunt elit esse laborum nisi. Magna quis cillum elit cupidatat qui velit amet consectetur mollit magna irure eiusmod. Duis occaecat enim aute nostrud elit non do in quis qui qui exercitation consequat et. Aliqua exercitation qui nostrud occaecat magna mollit elit aliquip ut ullamco incididunt mollit occaecat. In est aliqua nulla consequat sunt deserunt.\r\n",
    supervisor: "626fd9f88279c357591b949b",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f819799a5dee61951f",
    name: "Webb",
    goal: "Occaecat id officia cupidatat commodo aute exercitation mollit esse mollit amet proident velit eiusmod. Fugiat commodo ea exercitation commodo est esse duis magna adipisicing laborum esse irure. Do labore ullamco minim voluptate culpa Lorem proident fugiat.\r\n",
    supervisor: "626fd9f8f1751b741f1ca770",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f86ceba2e0e308005c",
    name: "Georgette",
    goal: "Deserunt cupidatat eu dolor culpa. Ullamco cupidatat sunt nulla consectetur mollit officia commodo eiusmod tempor excepteur nisi. Voluptate consequat incididunt tempor nulla elit aliquip veniam et aute. Occaecat minim enim in nulla non ea fugiat minim minim. Adipisicing consectetur duis aliqua tempor officia elit consequat occaecat ex ex veniam magna voluptate ex. Mollit quis Lorem ex cupidatat deserunt adipisicing. Id non et ex anim.\r\n",
    supervisor: "626fd9f8c71d87b49cccdf36",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f86196cc28d7e46d9f",
    name: "Bolton",
    goal: "Proident ipsum adipisicing aliqua culpa nisi officia voluptate mollit reprehenderit officia tempor non. Quis cillum proident ut duis labore pariatur enim veniam aliqua in occaecat. Deserunt mollit deserunt dolore nisi anim id do enim eiusmod commodo nisi dolore nostrud.\r\n",
    supervisor: "626fd9f8d9032c6e6a9df71b",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f867643c21ac62019e",
    name: "Duncan",
    goal: "Est amet quis consectetur dolore exercitation amet. Occaecat eu ea officia in pariatur tempor exercitation. Ea ea culpa ea sint elit est aliquip cillum nulla laborum. Laboris adipisicing enim occaecat sunt est. Qui cillum consequat tempor dolore pariatur sit sit proident commodo dolore.\r\n",
    supervisor: "626fd9f89f48771b8ab18751",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f809b1dba48a3c84dc",
    name: "Shelia",
    goal: "Excepteur do enim consequat pariatur commodo laborum. Mollit commodo consectetur elit minim id adipisicing laboris ut tempor et ipsum dolor duis. Ex ea aliquip elit do reprehenderit nostrud enim irure reprehenderit qui et. Laborum enim nostrud aliqua irure eiusmod duis. Deserunt dolore elit non anim. Reprehenderit culpa incididunt exercitation anim eiusmod est qui eu in qui ipsum excepteur ad.\r\n",
    supervisor: "626fd9f8ebaa3246c829a083",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f83ae98774d12c2b5c",
    name: "Jackie",
    goal: "Pariatur proident aute magna mollit dolor esse sunt reprehenderit excepteur nulla. Eiusmod quis aliqua enim in. Fugiat ut cupidatat incididunt ut aliqua ullamco aliquip. Officia sunt enim nisi adipisicing ad voluptate eiusmod excepteur.\r\n",
    supervisor: "626fd9f8a459619a261024e5",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f818d747862fa2974f",
    name: "Bray",
    goal: "Nisi irure mollit exercitation exercitation velit nostrud nisi. In sit qui aliqua magna duis ut occaecat qui id aliqua. Voluptate qui id non commodo nostrud nulla exercitation nulla quis est quis. Nulla Lorem enim culpa irure fugiat sint Lorem elit ea consectetur commodo veniam non. Ex culpa aute aute tempor mollit in consectetur sit ut eiusmod deserunt qui. Non ea eiusmod cupidatat deserunt Lorem duis occaecat proident laboris dolor ipsum. Nostrud culpa ut ad et.\r\n",
    supervisor: "626fd9f845921433e4589080",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f85249efd3ad9f419e",
    name: "Kristen",
    goal: "Anim do do officia in enim amet irure officia pariatur nostrud. Cupidatat est culpa aliquip exercitation nisi exercitation nisi. Velit veniam pariatur veniam pariatur occaecat dolor cillum labore. Consequat magna et incididunt nostrud sunt amet in sint deserunt mollit laboris veniam enim. Lorem veniam adipisicing adipisicing qui aliqua Lorem eiusmod. Ullamco elit do ullamco non.\r\n",
    supervisor: "626fd9f87a80a324ab577b16",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8253f1672491be227",
    name: "Nona",
    goal: "Enim consectetur anim laboris sit ut. Ea ad pariatur enim sint. Id labore eu nostrud aute nisi sint do excepteur eu eu pariatur anim. Ad esse proident incididunt consectetur. Dolor sit duis esse fugiat voluptate proident consectetur ipsum id reprehenderit aute velit consequat.\r\n",
    supervisor: "626fd9f852581208ab4371e6",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8f4acd492712e65bb",
    name: "Oconnor",
    goal: "Officia commodo laboris reprehenderit laboris enim incididunt et laboris cillum eu consectetur esse. Ex enim eu irure voluptate exercitation nostrud occaecat. Excepteur et eu irure consectetur culpa dolor aute esse aliquip tempor minim tempor. Irure aliqua do cupidatat commodo minim.\r\n",
    supervisor: "626fd9f8318fca5953030dba",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8773618a0d2b3cae2",
    name: "Wilkinson",
    goal: "Eiusmod sunt laboris irure labore commodo duis voluptate non magna ipsum ut exercitation. Reprehenderit elit in culpa ipsum tempor enim minim ullamco. Ad dolore magna eiusmod non adipisicing velit anim ex mollit commodo sint. Aliquip veniam aliqua velit labore officia sunt.\r\n",
    supervisor: "626fd9f88bc3557544dad45c",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f86f9a221eb185b213",
    name: "Boyd",
    goal: "Tempor elit veniam incididunt voluptate cillum reprehenderit cillum eiusmod fugiat officia et. Cupidatat nisi id sunt exercitation incididunt proident nulla eu sint reprehenderit est eiusmod. Lorem quis nostrud occaecat ea.\r\n",
    supervisor: "626fd9f889dbca6ec0ef7eea",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f83f23bb2ca4fefe7a",
    name: "Ora",
    goal: "Nisi in nisi aliquip et pariatur pariatur est. Proident nisi id eiusmod laborum minim ullamco ipsum non id ea aliquip ullamco. In commodo anim non cillum sint incididunt sunt ad labore nisi dolore velit duis proident. Nisi magna ullamco do aliqua amet amet. Ex velit anim nostrud velit.\r\n",
    supervisor: "626fd9f8e5026c89e4277f6c",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f818558b5e5ecf7623",
    name: "Della",
    goal: "Ex ea eiusmod labore est dolor aute eu. Consectetur ullamco voluptate reprehenderit adipisicing esse eiusmod ipsum voluptate velit. Esse anim eiusmod velit non aliquip laboris excepteur voluptate. Anim eu reprehenderit nostrud reprehenderit nostrud commodo deserunt aliqua adipisicing labore aliqua est.\r\n",
    supervisor: "626fd9f8670c39228dd770bc",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8d10f688e24d25625",
    name: "Esther",
    goal: "Tempor est duis enim qui enim esse non dolor Lorem est officia laboris nulla ullamco. Laboris in consequat aliqua laborum dolor in ullamco. Id incididunt aliquip est ex proident ad ad ad pariatur Lorem ea dolor cillum. Cillum eiusmod eiusmod incididunt officia anim velit occaecat. Esse duis ea consequat duis quis excepteur in adipisicing sit voluptate eiusmod nulla duis culpa.\r\n",
    supervisor: "626fd9f84538ff0f8ccd9a29",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8207bf7aaa5232313",
    name: "Hollie",
    goal: "Anim ipsum do ipsum cupidatat cupidatat ea velit sit consectetur sit. Est esse cupidatat exercitation laboris. In in cupidatat cupidatat id Lorem Lorem consectetur laboris. Nulla qui irure ipsum nulla officia fugiat sit minim in ut.\r\n",
    supervisor: "626fd9f81eba53abde6d8d13",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f873dbb44109c0fcb7",
    name: "Savannah",
    goal: "Id sunt incididunt exercitation dolore. Fugiat officia sit qui tempor anim laboris ullamco quis excepteur irure voluptate est voluptate adipisicing. Non cillum irure id incididunt in laboris consequat et labore.\r\n",
    supervisor: "626fd9f8b65656e0d4f976d8",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8f5d0599d83e475ce",
    name: "Adeline",
    goal: "Deserunt non voluptate deserunt pariatur cillum sint. Cupidatat eu consectetur consequat reprehenderit officia ipsum deserunt in sunt id et Lorem consectetur cupidatat. Qui et dolor nisi ea aute veniam incididunt aute nulla magna cillum magna et. Labore irure magna officia elit mollit reprehenderit ad id amet. Exercitation enim voluptate quis sint do reprehenderit veniam qui. Aliqua ullamco irure in non excepteur enim. In tempor Lorem et eu sint ullamco elit quis in.\r\n",
    supervisor: "626fd9f877b6a63b7840603b",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f871e1eee353c0942d",
    name: "Gina",
    goal: "Aute cillum nisi in officia elit anim fugiat culpa magna. Minim consequat proident nulla cillum qui veniam Lorem nisi est do Lorem eiusmod ipsum ut. Ex amet anim anim dolore laborum consequat est aliquip veniam. Laboris Lorem amet duis voluptate consequat labore magna elit reprehenderit adipisicing. Commodo Lorem ex esse quis eu proident amet ut nisi id anim ullamco excepteur eiusmod. Dolore ex excepteur pariatur mollit et et cupidatat enim ut est consequat consectetur non. Et deserunt consectetur ut officia duis occaecat eu laboris ut aliqua ut sit voluptate ad.\r\n",
    supervisor: "626fd9f800dfcf14b8c0a86c",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8dc9b36f049b65f2a",
    name: "Sykes",
    goal: "Elit elit proident adipisicing veniam in magna velit irure nostrud consectetur non. Mollit ad magna sit sint esse. Laboris sunt incididunt eu veniam sunt voluptate aliquip. Ullamco do Lorem nostrud deserunt quis ex et duis est.\r\n",
    supervisor: "626fd9f8b7016da1ac9ea0dd",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8114ac4549ca4bd09",
    name: "Copeland",
    goal: "Excepteur nisi ut ad nulla voluptate qui amet veniam velit. Nulla irure aliquip veniam dolore eu aliqua incididunt. Ullamco cillum dolore ad ad exercitation cupidatat laborum aliquip quis sunt duis cupidatat elit. Elit officia sint labore ipsum excepteur minim ipsum occaecat laboris cupidatat ad. Nisi consequat amet cillum ex non deserunt tempor ut nisi magna id nostrud incididunt veniam. Sit aliquip ipsum Lorem irure et dolor aliquip reprehenderit in nulla commodo cillum amet. Amet nostrud eiusmod ullamco sit nulla sunt irure dolore quis est ex excepteur.\r\n",
    supervisor: "626fd9f8667d093f121cd8a3",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8443c3d87093327e5",
    name: "Candace",
    goal: "Ea sit laborum est tempor ex minim anim proident sit. Ea in duis enim nostrud nisi voluptate. Adipisicing aliqua dolore qui nisi dolore labore esse laboris fugiat ullamco dolor enim excepteur.\r\n",
    supervisor: "626fd9f8a39537cdd4f5630e",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8a01c6030ddbe09bc",
    name: "Lori",
    goal: "Voluptate mollit est proident mollit dolor ea eiusmod tempor cillum qui sint. Eiusmod duis velit eu est enim ullamco dolor qui est sunt fugiat. Ad id aute ex ipsum mollit proident sunt velit adipisicing. Cupidatat in aute eiusmod minim magna nulla. Labore laboris culpa sunt est tempor ullamco consectetur sint non cillum duis voluptate sit cillum. Incididunt dolor occaecat cupidatat aliqua irure dolore laboris velit nostrud voluptate labore excepteur qui. Cillum occaecat cupidatat aliqua qui quis ea cillum consequat occaecat ea sint.\r\n",
    supervisor: "626fd9f8c16a48307134641c",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f850d9ec0400faf7a7",
    name: "Ayala",
    goal: "Dolor excepteur adipisicing id nisi amet do reprehenderit tempor velit magna. Ut id magna do duis in deserunt. Eiusmod tempor laborum elit velit voluptate. Fugiat laborum quis consequat pariatur duis labore ex in. Nisi aliquip consectetur consectetur aute nulla ut in pariatur ullamco incididunt sint aute proident do. Sit dolor commodo aute cupidatat sunt nostrud nulla quis ut. Adipisicing ipsum sint consectetur sunt elit ea.\r\n",
    supervisor: "626fd9f8f35d9567ef4e9db0",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8699a0f061172c817",
    name: "Page",
    goal: "Aliquip anim reprehenderit reprehenderit deserunt nulla deserunt Lorem laborum labore pariatur mollit ut aute elit. Do aliquip consectetur dolore tempor. Lorem pariatur quis do aute deserunt laboris ut commodo ut culpa veniam voluptate culpa cillum. Eiusmod in ullamco est et sunt. Tempor dolore labore enim commodo velit non reprehenderit ut magna aute quis id irure do.\r\n",
    supervisor: "626fd9f833b9b66e47b4561d",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8a366518f9b75c50b",
    name: "Woodard",
    goal: "Commodo nisi ullamco non ad voluptate pariatur velit occaecat minim ut proident eu. Nisi tempor qui ut culpa nostrud. Elit consectetur nostrud laborum proident veniam laboris minim aliquip est aute elit id. Quis ut duis incididunt ipsum pariatur nulla veniam amet proident. Pariatur laboris sunt cupidatat occaecat magna non quis deserunt officia quis proident elit irure nostrud.\r\n",
    supervisor: "626fd9f8e93a8291071e0576",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8cef4fb0b409d0717",
    name: "Green",
    goal: "Ipsum velit ea incididunt et. Irure aliquip incididunt magna culpa anim commodo tempor nostrud labore ut velit nulla consequat. Anim deserunt dolore enim dolor aute incididunt excepteur elit incididunt fugiat qui deserunt quis officia.\r\n",
    supervisor: "626fd9f8965cafb3d3f2ec3a",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f800c79167c6d70999",
    name: "Clarke",
    goal: "Laboris non exercitation aute amet. Ipsum do laboris ut amet occaecat eiusmod elit in id ipsum elit in ad laboris. In adipisicing eu amet aliqua cillum.\r\n",
    supervisor: "626fd9f841a23eef7b5afa4b",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8fb8a223acab75d44",
    name: "Kaufman",
    goal: "Esse qui ex mollit nisi. In commodo pariatur pariatur excepteur reprehenderit officia pariatur eiusmod sint. Velit officia enim consectetur exercitation ipsum dolore quis pariatur aliqua et minim.\r\n",
    supervisor: "626fd9f85b6add3c7acdfb4c",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8a6b31d3a2d3b4121",
    name: "Chapman",
    goal: "Qui ad commodo exercitation sit elit veniam excepteur fugiat fugiat incididunt fugiat. Cupidatat proident est commodo tempor elit nostrud esse labore voluptate mollit irure et deserunt. Elit anim deserunt exercitation ut nostrud officia veniam eiusmod laborum eiusmod deserunt reprehenderit id adipisicing. Qui aute reprehenderit in quis quis non quis nostrud sint ad proident ex. Proident ea fugiat ea adipisicing nulla. Do exercitation elit aliqua do. Laborum pariatur laboris occaecat mollit pariatur ex amet mollit deserunt sunt.\r\n",
    supervisor: "626fd9f806cf069779d48f5d",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f87a2dc49af1579a9c",
    name: "Riddle",
    goal: "Adipisicing laborum nisi ut aliquip incididunt dolore nulla ut pariatur. Aliqua mollit irure sit qui ut. Sit velit ullamco duis ad sunt elit esse laborum nisi. Magna quis cillum elit cupidatat qui velit amet consectetur mollit magna irure eiusmod. Duis occaecat enim aute nostrud elit non do in quis qui qui exercitation consequat et. Aliqua exercitation qui nostrud occaecat magna mollit elit aliquip ut ullamco incididunt mollit occaecat. In est aliqua nulla consequat sunt deserunt.\r\n",
    supervisor: "626fd9f88279c357591b949b",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f819799a5dee61951f",
    name: "Webb",
    goal: "Occaecat id officia cupidatat commodo aute exercitation mollit esse mollit amet proident velit eiusmod. Fugiat commodo ea exercitation commodo est esse duis magna adipisicing laborum esse irure. Do labore ullamco minim voluptate culpa Lorem proident fugiat.\r\n",
    supervisor: "626fd9f8f1751b741f1ca770",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f86ceba2e0e308005c",
    name: "Georgette",
    goal: "Deserunt cupidatat eu dolor culpa. Ullamco cupidatat sunt nulla consectetur mollit officia commodo eiusmod tempor excepteur nisi. Voluptate consequat incididunt tempor nulla elit aliquip veniam et aute. Occaecat minim enim in nulla non ea fugiat minim minim. Adipisicing consectetur duis aliqua tempor officia elit consequat occaecat ex ex veniam magna voluptate ex. Mollit quis Lorem ex cupidatat deserunt adipisicing. Id non et ex anim.\r\n",
    supervisor: "626fd9f8c71d87b49cccdf36",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f86196cc28d7e46d9f",
    name: "Bolton",
    goal: "Proident ipsum adipisicing aliqua culpa nisi officia voluptate mollit reprehenderit officia tempor non. Quis cillum proident ut duis labore pariatur enim veniam aliqua in occaecat. Deserunt mollit deserunt dolore nisi anim id do enim eiusmod commodo nisi dolore nostrud.\r\n",
    supervisor: "626fd9f8d9032c6e6a9df71b",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f867643c21ac62019e",
    name: "Duncan",
    goal: "Est amet quis consectetur dolore exercitation amet. Occaecat eu ea officia in pariatur tempor exercitation. Ea ea culpa ea sint elit est aliquip cillum nulla laborum. Laboris adipisicing enim occaecat sunt est. Qui cillum consequat tempor dolore pariatur sit sit proident commodo dolore.\r\n",
    supervisor: "626fd9f89f48771b8ab18751",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f809b1dba48a3c84dc",
    name: "Shelia",
    goal: "Excepteur do enim consequat pariatur commodo laborum. Mollit commodo consectetur elit minim id adipisicing laboris ut tempor et ipsum dolor duis. Ex ea aliquip elit do reprehenderit nostrud enim irure reprehenderit qui et. Laborum enim nostrud aliqua irure eiusmod duis. Deserunt dolore elit non anim. Reprehenderit culpa incididunt exercitation anim eiusmod est qui eu in qui ipsum excepteur ad.\r\n",
    supervisor: "626fd9f8ebaa3246c829a083",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f83ae98774d12c2b5c",
    name: "Jackie",
    goal: "Pariatur proident aute magna mollit dolor esse sunt reprehenderit excepteur nulla. Eiusmod quis aliqua enim in. Fugiat ut cupidatat incididunt ut aliqua ullamco aliquip. Officia sunt enim nisi adipisicing ad voluptate eiusmod excepteur.\r\n",
    supervisor: "626fd9f8a459619a261024e5",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f818d747862fa2974f",
    name: "Bray",
    goal: "Nisi irure mollit exercitation exercitation velit nostrud nisi. In sit qui aliqua magna duis ut occaecat qui id aliqua. Voluptate qui id non commodo nostrud nulla exercitation nulla quis est quis. Nulla Lorem enim culpa irure fugiat sint Lorem elit ea consectetur commodo veniam non. Ex culpa aute aute tempor mollit in consectetur sit ut eiusmod deserunt qui. Non ea eiusmod cupidatat deserunt Lorem duis occaecat proident laboris dolor ipsum. Nostrud culpa ut ad et.\r\n",
    supervisor: "626fd9f845921433e4589080",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f85249efd3ad9f419e",
    name: "Kristen",
    goal: "Anim do do officia in enim amet irure officia pariatur nostrud. Cupidatat est culpa aliquip exercitation nisi exercitation nisi. Velit veniam pariatur veniam pariatur occaecat dolor cillum labore. Consequat magna et incididunt nostrud sunt amet in sint deserunt mollit laboris veniam enim. Lorem veniam adipisicing adipisicing qui aliqua Lorem eiusmod. Ullamco elit do ullamco non.\r\n",
    supervisor: "626fd9f87a80a324ab577b16",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8253f1672491be227",
    name: "Nona",
    goal: "Enim consectetur anim laboris sit ut. Ea ad pariatur enim sint. Id labore eu nostrud aute nisi sint do excepteur eu eu pariatur anim. Ad esse proident incididunt consectetur. Dolor sit duis esse fugiat voluptate proident consectetur ipsum id reprehenderit aute velit consequat.\r\n",
    supervisor: "626fd9f852581208ab4371e6",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8f4acd492712e65bb",
    name: "Oconnor",
    goal: "Officia commodo laboris reprehenderit laboris enim incididunt et laboris cillum eu consectetur esse. Ex enim eu irure voluptate exercitation nostrud occaecat. Excepteur et eu irure consectetur culpa dolor aute esse aliquip tempor minim tempor. Irure aliqua do cupidatat commodo minim.\r\n",
    supervisor: "626fd9f8318fca5953030dba",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8773618a0d2b3cae2",
    name: "Wilkinson",
    goal: "Eiusmod sunt laboris irure labore commodo duis voluptate non magna ipsum ut exercitation. Reprehenderit elit in culpa ipsum tempor enim minim ullamco. Ad dolore magna eiusmod non adipisicing velit anim ex mollit commodo sint. Aliquip veniam aliqua velit labore officia sunt.\r\n",
    supervisor: "626fd9f88bc3557544dad45c",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f86f9a221eb185b213",
    name: "Boyd",
    goal: "Tempor elit veniam incididunt voluptate cillum reprehenderit cillum eiusmod fugiat officia et. Cupidatat nisi id sunt exercitation incididunt proident nulla eu sint reprehenderit est eiusmod. Lorem quis nostrud occaecat ea.\r\n",
    supervisor: "626fd9f889dbca6ec0ef7eea",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f83f23bb2ca4fefe7a",
    name: "Ora",
    goal: "Nisi in nisi aliquip et pariatur pariatur est. Proident nisi id eiusmod laborum minim ullamco ipsum non id ea aliquip ullamco. In commodo anim non cillum sint incididunt sunt ad labore nisi dolore velit duis proident. Nisi magna ullamco do aliqua amet amet. Ex velit anim nostrud velit.\r\n",
    supervisor: "626fd9f8e5026c89e4277f6c",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f818558b5e5ecf7623",
    name: "Della",
    goal: "Ex ea eiusmod labore est dolor aute eu. Consectetur ullamco voluptate reprehenderit adipisicing esse eiusmod ipsum voluptate velit. Esse anim eiusmod velit non aliquip laboris excepteur voluptate. Anim eu reprehenderit nostrud reprehenderit nostrud commodo deserunt aliqua adipisicing labore aliqua est.\r\n",
    supervisor: "626fd9f8670c39228dd770bc",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8d10f688e24d25625",
    name: "Esther",
    goal: "Tempor est duis enim qui enim esse non dolor Lorem est officia laboris nulla ullamco. Laboris in consequat aliqua laborum dolor in ullamco. Id incididunt aliquip est ex proident ad ad ad pariatur Lorem ea dolor cillum. Cillum eiusmod eiusmod incididunt officia anim velit occaecat. Esse duis ea consequat duis quis excepteur in adipisicing sit voluptate eiusmod nulla duis culpa.\r\n",
    supervisor: "626fd9f84538ff0f8ccd9a29",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8207bf7aaa5232313",
    name: "Hollie",
    goal: "Anim ipsum do ipsum cupidatat cupidatat ea velit sit consectetur sit. Est esse cupidatat exercitation laboris. In in cupidatat cupidatat id Lorem Lorem consectetur laboris. Nulla qui irure ipsum nulla officia fugiat sit minim in ut.\r\n",
    supervisor: "626fd9f81eba53abde6d8d13",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f873dbb44109c0fcb7",
    name: "Savannah",
    goal: "Id sunt incididunt exercitation dolore. Fugiat officia sit qui tempor anim laboris ullamco quis excepteur irure voluptate est voluptate adipisicing. Non cillum irure id incididunt in laboris consequat et labore.\r\n",
    supervisor: "626fd9f8b65656e0d4f976d8",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8f5d0599d83e475ce",
    name: "Adeline",
    goal: "Deserunt non voluptate deserunt pariatur cillum sint. Cupidatat eu consectetur consequat reprehenderit officia ipsum deserunt in sunt id et Lorem consectetur cupidatat. Qui et dolor nisi ea aute veniam incididunt aute nulla magna cillum magna et. Labore irure magna officia elit mollit reprehenderit ad id amet. Exercitation enim voluptate quis sint do reprehenderit veniam qui. Aliqua ullamco irure in non excepteur enim. In tempor Lorem et eu sint ullamco elit quis in.\r\n",
    supervisor: "626fd9f877b6a63b7840603b",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f871e1eee353c0942d",
    name: "Gina",
    goal: "Aute cillum nisi in officia elit anim fugiat culpa magna. Minim consequat proident nulla cillum qui veniam Lorem nisi est do Lorem eiusmod ipsum ut. Ex amet anim anim dolore laborum consequat est aliquip veniam. Laboris Lorem amet duis voluptate consequat labore magna elit reprehenderit adipisicing. Commodo Lorem ex esse quis eu proident amet ut nisi id anim ullamco excepteur eiusmod. Dolore ex excepteur pariatur mollit et et cupidatat enim ut est consequat consectetur non. Et deserunt consectetur ut officia duis occaecat eu laboris ut aliqua ut sit voluptate ad.\r\n",
    supervisor: "626fd9f800dfcf14b8c0a86c",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8dc9b36f049b65f2a",
    name: "Sykes",
    goal: "Elit elit proident adipisicing veniam in magna velit irure nostrud consectetur non. Mollit ad magna sit sint esse. Laboris sunt incididunt eu veniam sunt voluptate aliquip. Ullamco do Lorem nostrud deserunt quis ex et duis est.\r\n",
    supervisor: "626fd9f8b7016da1ac9ea0dd",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8114ac4549ca4bd09",
    name: "Copeland",
    goal: "Excepteur nisi ut ad nulla voluptate qui amet veniam velit. Nulla irure aliquip veniam dolore eu aliqua incididunt. Ullamco cillum dolore ad ad exercitation cupidatat laborum aliquip quis sunt duis cupidatat elit. Elit officia sint labore ipsum excepteur minim ipsum occaecat laboris cupidatat ad. Nisi consequat amet cillum ex non deserunt tempor ut nisi magna id nostrud incididunt veniam. Sit aliquip ipsum Lorem irure et dolor aliquip reprehenderit in nulla commodo cillum amet. Amet nostrud eiusmod ullamco sit nulla sunt irure dolore quis est ex excepteur.\r\n",
    supervisor: "626fd9f8667d093f121cd8a3",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8443c3d87093327e5",
    name: "Candace",
    goal: "Ea sit laborum est tempor ex minim anim proident sit. Ea in duis enim nostrud nisi voluptate. Adipisicing aliqua dolore qui nisi dolore labore esse laboris fugiat ullamco dolor enim excepteur.\r\n",
    supervisor: "626fd9f8a39537cdd4f5630e",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8a01c6030ddbe09bc",
    name: "Lori",
    goal: "Voluptate mollit est proident mollit dolor ea eiusmod tempor cillum qui sint. Eiusmod duis velit eu est enim ullamco dolor qui est sunt fugiat. Ad id aute ex ipsum mollit proident sunt velit adipisicing. Cupidatat in aute eiusmod minim magna nulla. Labore laboris culpa sunt est tempor ullamco consectetur sint non cillum duis voluptate sit cillum. Incididunt dolor occaecat cupidatat aliqua irure dolore laboris velit nostrud voluptate labore excepteur qui. Cillum occaecat cupidatat aliqua qui quis ea cillum consequat occaecat ea sint.\r\n",
    supervisor: "626fd9f8c16a48307134641c",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f850d9ec0400faf7a7",
    name: "Ayala",
    goal: "Dolor excepteur adipisicing id nisi amet do reprehenderit tempor velit magna. Ut id magna do duis in deserunt. Eiusmod tempor laborum elit velit voluptate. Fugiat laborum quis consequat pariatur duis labore ex in. Nisi aliquip consectetur consectetur aute nulla ut in pariatur ullamco incididunt sint aute proident do. Sit dolor commodo aute cupidatat sunt nostrud nulla quis ut. Adipisicing ipsum sint consectetur sunt elit ea.\r\n",
    supervisor: "626fd9f8f35d9567ef4e9db0",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8699a0f061172c817",
    name: "Page",
    goal: "Aliquip anim reprehenderit reprehenderit deserunt nulla deserunt Lorem laborum labore pariatur mollit ut aute elit. Do aliquip consectetur dolore tempor. Lorem pariatur quis do aute deserunt laboris ut commodo ut culpa veniam voluptate culpa cillum. Eiusmod in ullamco est et sunt. Tempor dolore labore enim commodo velit non reprehenderit ut magna aute quis id irure do.\r\n",
    supervisor: "626fd9f833b9b66e47b4561d",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8a366518f9b75c50b",
    name: "Woodard",
    goal: "Commodo nisi ullamco non ad voluptate pariatur velit occaecat minim ut proident eu. Nisi tempor qui ut culpa nostrud. Elit consectetur nostrud laborum proident veniam laboris minim aliquip est aute elit id. Quis ut duis incididunt ipsum pariatur nulla veniam amet proident. Pariatur laboris sunt cupidatat occaecat magna non quis deserunt officia quis proident elit irure nostrud.\r\n",
    supervisor: "626fd9f8e93a8291071e0576",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8cef4fb0b409d0717",
    name: "Green",
    goal: "Ipsum velit ea incididunt et. Irure aliquip incididunt magna culpa anim commodo tempor nostrud labore ut velit nulla consequat. Anim deserunt dolore enim dolor aute incididunt excepteur elit incididunt fugiat qui deserunt quis officia.\r\n",
    supervisor: "626fd9f8965cafb3d3f2ec3a",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f800c79167c6d70999",
    name: "Clarke",
    goal: "Laboris non exercitation aute amet. Ipsum do laboris ut amet occaecat eiusmod elit in id ipsum elit in ad laboris. In adipisicing eu amet aliqua cillum.\r\n",
    supervisor: "626fd9f841a23eef7b5afa4b",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8fb8a223acab75d44",
    name: "Kaufman",
    goal: "Esse qui ex mollit nisi. In commodo pariatur pariatur excepteur reprehenderit officia pariatur eiusmod sint. Velit officia enim consectetur exercitation ipsum dolore quis pariatur aliqua et minim.\r\n",
    supervisor: "626fd9f85b6add3c7acdfb4c",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f8a6b31d3a2d3b4121",
    name: "Chapman",
    goal: "Qui ad commodo exercitation sit elit veniam excepteur fugiat fugiat incididunt fugiat. Cupidatat proident est commodo tempor elit nostrud esse labore voluptate mollit irure et deserunt. Elit anim deserunt exercitation ut nostrud officia veniam eiusmod laborum eiusmod deserunt reprehenderit id adipisicing. Qui aute reprehenderit in quis quis non quis nostrud sint ad proident ex. Proident ea fugiat ea adipisicing nulla. Do exercitation elit aliqua do. Laborum pariatur laboris occaecat mollit pariatur ex amet mollit deserunt sunt.\r\n",
    supervisor: "626fd9f806cf069779d48f5d",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f87a2dc49af1579a9c",
    name: "Riddle",
    goal: "Adipisicing laborum nisi ut aliquip incididunt dolore nulla ut pariatur. Aliqua mollit irure sit qui ut. Sit velit ullamco duis ad sunt elit esse laborum nisi. Magna quis cillum elit cupidatat qui velit amet consectetur mollit magna irure eiusmod. Duis occaecat enim aute nostrud elit non do in quis qui qui exercitation consequat et. Aliqua exercitation qui nostrud occaecat magna mollit elit aliquip ut ullamco incididunt mollit occaecat. In est aliqua nulla consequat sunt deserunt.\r\n",
    supervisor: "626fd9f88279c357591b949b",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f819799a5dee61951f",
    name: "Webb",
    goal: "Occaecat id officia cupidatat commodo aute exercitation mollit esse mollit amet proident velit eiusmod. Fugiat commodo ea exercitation commodo est esse duis magna adipisicing laborum esse irure. Do labore ullamco minim voluptate culpa Lorem proident fugiat.\r\n",
    supervisor: "626fd9f8f1751b741f1ca770",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
  {
    id: "626fd9f86ceba2e0e308005c",
    name: "Georgette",
    goal: "Deserunt cupidatat eu dolor culpa. Ullamco cupidatat sunt nulla consectetur mollit officia commodo eiusmod tempor excepteur nisi. Voluptate consequat incididunt tempor nulla elit aliquip veniam et aute. Occaecat minim enim in nulla non ea fugiat minim minim. Adipisicing consectetur duis aliqua tempor officia elit consequat occaecat ex ex veniam magna voluptate ex. Mollit quis Lorem ex cupidatat deserunt adipisicing. Id non et ex anim.\r\n",
    supervisor: "626fd9f8c71d87b49cccdf36",
    teachers: [0, 10],
    students: [10, 11, 30, 42],
    degree: "MASTER",
    language: "cs",
    studyProgramme: 0,
  },
];

